apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: phishing-daemon
  namespace: phishing-detection
spec:
  selector:
    matchLabels:
      app: phishing-daemon
  template:
    metadata:
      labels:
        app: phishing-daemon
    spec:
      containers:
      - name: phishing-daemon
        image: anitalluri00/phishing-detection-ps
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: phishing-config
