apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: phishing-hpa
  namespace: phishing-detection
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phishing-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
